# Generated by Django 5.2.14 on 2026-06-04 21:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('pastor', 'Lider Principal'),
                        ('secretary', 'Secretario'),
                        ('leader', 'Lider'),
                        ('treasurer', 'Tesoureiro'),
                        ('member', 'Membro'),
                    ],
                    max_length=20,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('pastor', 'Lider Principal'),
                        ('secretary', 'Secretario'),
                        ('leader', 'Lider'),
                        ('treasurer', 'Tesoureiro'),
                        ('member', 'Membro'),
                    ],
                    max_length=20,
                ),
                blank=True,
                default=list,
                help_text='Lista de papeis. Permissoes sao a uniao das permissoes de cada papel.',
                size=None,
            ),
        ),
    ]
