# Generated by Django 5.2.14 on 2026-06-04 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('visitor', 'Visitante'),
                            ('congregant', 'Congregado'),
                            ('member', 'Membro'),
                            ('leader', 'Lider'),
                            ('inactive', 'Inativo'),
                        ],
                        db_index=True,
                        default='visitor',
                        max_length=12,
                    ),
                ),
                (
                    'consent_given_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Obrigatorio quando email ou telefone esta preenchido (LGPD).',
                        null=True,
                    ),
                ),
                (
                    'anonymized_at',
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ('notes', models.TextField(blank=True, default='')),
                (
                    'community',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='members',
                        to='communities.community',
                    ),
                ),
                (
                    'ministries',
                    models.ManyToManyField(
                        blank=True, related_name='members', to='ministries.ministry'
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
