# Generated by Django 5.2.14 on 2026-06-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
