# Generated by Django 5.2.14 on 2026-06-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='import_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
