# Generated by Django 5.2.14 on 2026-06-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_import_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='joined_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
