# Generated by Django 5.2.14 on 2026-06-05 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0003_remove_community_leader_community_leaders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gathering',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'gathering_type',
                    models.CharField(
                        choices=[
                            ('worship', 'Culto'),
                            ('community', 'Reuniao de Comunidade'),
                            ('event', 'Evento'),
                            ('meeting', 'Reuniao'),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True, default='')),
                (
                    'created_by',
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    'community',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='gatherings',
                        to='communities.community',
                    ),
                ),
            ],
            options={
                'ordering': ('-date', '-created_at'),
            },
        ),
    ]
