# Generated by Django 5.2.14 on 2026-06-05 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0001_initial'),
        ('people', '0003_person_import_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_present', models.BooleanField(default=True)),
                (
                    'gathering',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attendances',
                        to='gatherings.gathering',
                    ),
                ),
                (
                    'person',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='attendances',
                        to='people.person',
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('person', 'gathering')},
            },
        ),
    ]
