# Generated by Django 5.2.14 on 2026-06-11 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0002_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.IntegerField(blank=True, db_index=True, null=True)),
                ('gathering', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='gatherings.gathering')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
