# Generated by Django 5.2.14 on 2026-06-10 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_person_import_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                (
                    'kind',
                    models.CharField(
                        choices=[('income', 'Entrada'), ('expense', 'Saída')],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('kind', 'name'),
                'constraints': [
                    models.UniqueConstraint(
                        fields=('name', 'kind'),
                        name='finance_category_unique_name_kind',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    'description',
                    models.CharField(blank=True, default='', max_length=200),
                ),
                (
                    'payment_method',
                    models.CharField(
                        choices=[
                            ('cash', 'Dinheiro'),
                            ('pix', 'Pix'),
                            ('card', 'Cartão'),
                            ('transfer', 'Transferência'),
                            ('other', 'Outro'),
                        ],
                        default='cash',
                        max_length=12,
                    ),
                ),
                (
                    'created_by',
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='transactions',
                        to='finance.category',
                    ),
                ),
                (
                    'contributor',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='contributions',
                        to='people.person',
                    ),
                ),
            ],
            options={
                'ordering': ('-date', '-created_at'),
            },
        ),
    ]
