# Generated by Django 5.2.14 on 2026-06-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0002_initial'),
        ('people', '0002_person_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministry',
            name='coordinator',
        ),
        migrations.AddField(
            model_name='ministry',
            name='coordinators',
            field=models.ManyToManyField(
                blank=True, related_name='ministries_led', to='people.person'
            ),
        ),
    ]
