# Generated by Django 5.2.14 on 2026-06-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0004_ministry_volunteers_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='category',
            field=models.CharField(
                choices=[
                    ('worship', 'Adoracao'),
                    ('kids', 'Criancas'),
                    ('media', 'Midia'),
                    ('service', 'Servico'),
                    ('welcome', 'Acolhimento'),
                    ('teaching', 'Ensino'),
                    ('other', 'Outro'),
                ],
                default='other',
                max_length=10,
            ),
        ),
    ]
