# Generated by Django 5.2.14 on 2026-06-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('user_id', models.IntegerField(null=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=60)),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('login_success', 'Login bem-sucedido'),
                            ('login_failure', 'Login falho'),
                            ('lockout', 'Lockout (axes)'),
                            ('password_reset_requested', 'Reset de senha solicitado'),
                            ('password_reset_completed', 'Reset de senha concluido'),
                            ('role_change', 'Mudanca de papel'),
                            ('user_deactivated', 'Usuario desativado'),
                            ('user_reactivated', 'Usuario reativado'),
                            ('person_exported', 'Pessoa exportada'),
                            ('person_anonymized', 'Pessoa anonimizada'),
                            ('platform_admin_access', 'Acesso de Platform Admin'),
                            ('sensitive_file_upload', 'Upload de arquivo sensivel'),
                            ('sensitive_file_download', 'Download de arquivo sensivel'),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'user_id',
                    models.IntegerField(
                        help_text='User.id no schema public', null=True
                    ),
                ),
                (
                    'tenant_id',
                    models.CharField(
                        db_index=True,
                        help_text='Schema name do tenant, injetado pelo TenantMiddleware',
                        max_length=60,
                    ),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('create', 'Criacao'),
                            ('read', 'Leitura'),
                            ('update', 'Alteracao'),
                            ('delete', 'Exclusao'),
                            ('export', 'Exportacao'),
                            ('anonymize', 'Anonimizacao'),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ('model_name', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=40)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(
                        fields=['tenant_id', 'action'],
                        name='core_auditl_tenant__f59c2a_idx',
                    ),
                    models.Index(
                        fields=['tenant_id', 'model_name', 'object_id'],
                        name='core_auditl_tenant__27ba11_idx',
                    ),
                ],
            },
        ),
    ]
