# Generated by Django 5.2.14 on 2026-06-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_securitylog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('login_success', 'Login bem-sucedido'),
                    ('login_failure', 'Login falho'),
                    ('lockout', 'Lockout (axes)'),
                    ('password_reset_requested', 'Reset de senha solicitado'),
                    ('password_reset_completed', 'Reset de senha concluido'),
                    ('role_change', 'Mudanca de papel'),
                    ('user_deactivated', 'Usuario desativado'),
                    ('user_reactivated', 'Usuario reativado'),
                    ('mfa_enabled', 'MFA ativado'),
                    ('mfa_disabled', 'MFA desativado'),
                    ('person_exported', 'Pessoa exportada'),
                    ('person_anonymized', 'Pessoa anonimizada'),
                    ('platform_admin_access', 'Acesso de Platform Admin'),
                    ('support_access_granted', 'Acesso de suporte concedido'),
                    ('support_access_revoked', 'Acesso de suporte revogado'),
                    ('sensitive_file_upload', 'Upload de arquivo sensivel'),
                    ('sensitive_file_download', 'Download de arquivo sensivel'),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
