# Generated by Django 5.2.14 on 2026-06-01 21:50

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'schema_name',
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ('name', models.CharField(max_length=120)),
                ('slug', models.CharField(max_length=60, unique=True)),
                (
                    'leader_title',
                    models.CharField(
                        default='Pastor',
                        help_text='Titulo do lider principal (Pastor, Padre, Reverendo, etc.)',
                        max_length=40,
                    ),
                ),
                (
                    'has_communities',
                    models.BooleanField(
                        default=True,
                        help_text='True = igreja em celulas. False = tradicional.',
                    ),
                ),
                ('accent_color', models.CharField(default='#7C3F06', max_length=7)),
                ('hot_color', models.CharField(default='#FF9C1A', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('privacy_policy_url', models.URLField(blank=True, default='')),
                (
                    'plan',
                    models.CharField(
                        choices=[
                            ('free', 'Gratis (ate 50 pessoas)'),
                            ('basic', 'Basico (ate 200 pessoas)'),
                            ('pro', 'Profissional (pessoas ilimitadas)'),
                        ],
                        default='free',
                        max_length=10,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                (
                    'name',
                    models.CharField(
                        choices=[
                            ('free', 'Gratis (ate 50 pessoas)'),
                            ('basic', 'Basico (ate 200 pessoas)'),
                            ('pro', 'Profissional (pessoas ilimitadas)'),
                        ],
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'max_persons',
                    models.PositiveIntegerField(default=50, help_text='0 = ilimitado'),
                ),
                (
                    'max_communities',
                    models.PositiveIntegerField(default=5, help_text='0 = ilimitado'),
                ),
                (
                    'price_monthly',
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'domain',
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='domains',
                        to='tenants.church',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
