# Generated by Django 5.2.14 on 2026-06-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='accent_color',
            field=models.CharField(default='#C75A3B', max_length=7),
        ),
        migrations.AlterField(
            model_name='church',
            name='hot_color',
            field=models.CharField(default='#E09A2D', max_length=7),
        ),
    ]
