# Generated by Django 5.2.14 on 2026-06-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='accent_color',
            field=models.CharField(default='#864507', max_length=7),
        ),
        migrations.AlterField(
            model_name='church',
            name='hot_color',
            field=models.CharField(default='#F59A17', max_length=7),
        ),
    ]
