# Generated by Django 5.2.14 on 2026-06-11 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_church_accent_color_alter_church_hot_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='schedule_pending_open_day',
            field=models.PositiveSmallIntegerField(
                default=25,
                help_text='Dia em que abrem as pendencias de escala do mes seguinte (1-28).',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(28),
                ],
            ),
        ),
    ]
