# Generated by Django 5.2.14 on 2026-06-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_church_schedule_pending_open_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='community_label',
            field=models.CharField(
                default='Comunidade',
                help_text='Como esta igreja chama a Comunidade (ex.: Celula, Grupo, GC).',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='church',
            name='community_label_plural',
            field=models.CharField(default='Comunidades', max_length=30),
        ),
        migrations.AddField(
            model_name='church',
            name='ministry_label',
            field=models.CharField(
                default='Ministério',
                help_text='Como esta igreja chama o Ministerio (ex.: Departamento, Equipe).',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='church',
            name='ministry_label_plural',
            field=models.CharField(default='Ministérios', max_length=30),
        ),
    ]
