# Generated by Django 5.2.14 on 2026-06-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
        ('people', '0002_person_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='leader',
        ),
        migrations.AddField(
            model_name='community',
            name='leaders',
            field=models.ManyToManyField(
                blank=True, related_name='communities_led', to='people.person'
            ),
        ),
    ]
