# Generated by Django 5.2.14 on 2026-06-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_remove_community_leader_community_leaders'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.CharField(
                choices=[
                    ('mixed', 'Mista'),
                    ('youth', 'Jovens'),
                    ('couples', 'Casais'),
                    ('women', 'Mulheres'),
                    ('men', 'Homens'),
                    ('kids', 'Criancas'),
                    ('other', 'Outra'),
                ],
                default='mixed',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='community',
            name='max_members',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
