# Generated by Django 5.2.14 on 2026-06-05 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatherings', '0002_attendance'),
        ('ministries', '0003_remove_ministry_coordinator_ministry_coordinators'),
        ('people', '0003_person_import_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, default='', max_length=60)),
                ('notes', models.TextField(blank=True, default='')),
                (
                    'gathering',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='schedules',
                        to='gatherings.gathering',
                    ),
                ),
                (
                    'ministry',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='schedules',
                        to='ministries.ministry',
                    ),
                ),
                (
                    'person',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='schedules',
                        to='people.person',
                    ),
                ),
            ],
            options={
                'ordering': ('-gathering__date', 'ministry__name'),
            },
        ),
        migrations.CreateModel(
            name='ScheduleConflictApproval',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'approved_by_id',
                    models.IntegerField(help_text='User.id do aprovador competente'),
                ),
                ('justification', models.TextField()),
                ('approved_at', models.DateTimeField()),
                (
                    'schedule',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='conflict_approvals',
                        to='schedules.schedule',
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
