# Generated by Django 5.2.14 on 2026-06-11 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0003_attendancesession'),
        ('ministries', '0004_ministry_volunteers_needed'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryEventOptOut',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'marked_by_id',
                    models.IntegerField(help_text='User.id do coordenador que marcou'),
                ),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                (
                    'gathering',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ministry_optouts',
                        to='gatherings.gathering',
                    ),
                ),
                (
                    'ministry',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='event_optouts',
                        to='ministries.ministry',
                    ),
                ),
            ],
            options={
                'ordering': ('-gathering__date',),
                'unique_together': {('ministry', 'gathering')},
            },
        ),
    ]
