# Generated by Django 5.2.14 on 2026-06-05 13:32

import apps.core.storage
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'file',
                    models.FileField(
                        max_length=500,
                        upload_to=apps.core.storage.tenant_upload_path,
                        validators=[apps.core.validators.MagicValidator()],
                        verbose_name='arquivo',
                    ),
                ),
                (
                    'filename',
                    models.CharField(max_length=255, verbose_name='nome original'),
                ),
                (
                    'mime_type',
                    models.CharField(max_length=80, verbose_name='tipo MIME detectado'),
                ),
                (
                    'size_bytes',
                    models.PositiveIntegerField(verbose_name='tamanho em bytes'),
                ),
                (
                    'storage_path',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=500,
                        verbose_name='caminho no storage',
                    ),
                ),
                (
                    'uploaded_by_id',
                    models.IntegerField(
                        help_text='accounts.User.id no schema public',
                        null=True,
                        verbose_name='enviado por',
                    ),
                ),
                (
                    'related_model',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=80,
                        verbose_name='model relacionado',
                    ),
                ),
                (
                    'related_object_id',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=40,
                        verbose_name='id do objeto relacionado',
                    ),
                ),
            ],
            options={
                'verbose_name': 'arquivo',
                'verbose_name_plural': 'arquivos',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [
                    models.Index(
                        fields=['related_model', 'related_object_id'],
                        name='files_filea_related_b81886_idx',
                    )
                ],
            },
        ),
    ]
